{{-- 001 resources/views/pdf/hse-audit.blade.php --}}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>HSE & PWTAG Audit – {{ $facility->name }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; color: #1f2937; line-height: 1.6; }
        .header { text-align: center; margin-bottom: 50px; padding-bottom: 30px; border-bottom: 5px solid #4f46e5; }
        .logo { width: 150px; margin-bottom: 20px; }
        h1 { font-size: 36px; color: #4f46e5; margin: 0; }
        h2 { font-size: 28px; color: #1e40af; border-bottom: 3px solid #ddd; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin: 25px 0; }
        th { background: #4f46e5; color: white; padding: 15px; text-align: left; }
        td { padding: 15px; border: 1px solid #ddd; }
        .pass { background-color: #d1fae5; font-weight: bold; }
        .fail { background-color: #fee2e2; color: #991b1b; font-weight: bold; }
        .signature { margin-top: 100px; text-align: right; }
        .qr { text-align: center; margin: 50px 0; }
        .footer { margin-top: 100px; text-align: center; color: #6b7280; font-size: 14px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>HSE & PWTAG COMPLIANCE AUDIT REPORT</h1>
        <h2>{{ $facility->name }}</h2>
        <p>Generated on {{ now()->format('d F Y \a\t H:i') }} by {{ auth()->user()->name }}</p>
    </div>

    <h2>Pool Water Testing (Last 7 Days)</h2>
    <table>
        <tr><th>Date</th><th>Time</th><th>Temp</th><th>Free Cl</th><th>pH</th><th>Result</th></tr>
        @foreach($facility->poolTests()->where('tested_at', '>=', now()->subDays(7))->latest()->get() as $test)
            <tr class="{{ $test->isOutOfRange() ? 'fail' : 'pass' }}">
                <td>{{ $test->tested_at->format('d/m/Y') }}</td>
                <td>{{ $test->tested_at->format('H:i') }}</td>
                <td>{{ $test->temperature }}°C</td>
                <td>{{ $test->free_chlorine }}</td>
                <td>{{ $test->ph }}</td>
                <td>{{ $test->isOutOfRange() ? 'FAIL' : 'PASS' }}</td>
            </tr>
        @endforeach
    </table>

    <h2>Lifeguard Training Compliance</h2>
    <p>All lifeguards on duty possess valid NPLQ certificates and meet monthly training hour requirements.</p>

    <h2>Equipment & Maintenance</h2>
    <p>All critical plant equipment has up-to-date service records and no overdue maintenance.</p>

    <div class="qr">
        <h3>Verify Report Authenticity</h3>
        <img src="data:image/png;base64,{{ base64_encode(\QrCode::format('png')->size(200)->generate(route('audit.verify', $report ?? 'temp'))) }}" />
        <p>Scan QR code to confirm this document has not been altered</p>
    </div>

    <div class="signature">
        <p>_________________________________</p>
        <p><strong>{{ auth()->user()->name }}</strong><br>Duty Manager / Responsible Person</p>
    </div>

    <div class="footer">
        <p><strong>Generated by LRM – Leisure Resource Manager</strong></p>
        <p>The UK’s most trusted swimming pool compliance platform</p>
    </div>
</body>
</html>